# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4453bf9f1eda6e6a56b26686bbdc41e58d5769246198cee1ebfeb1dc249b05daf96712a3d6abd653ab117187c5737fda061b0207be7e10ead795251466f3abce

test:
  secret_key_base: 4d47246e26030f30227e61f445de1ddb6847166626244657a0e9570087362de717413f38f5e5e6383606e3062d1ed9743a075fe87b5ef026d852f461fc82f2f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
